language: python
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
install:
  - pip install -r requirements.txt
# command to run tests
script:
  pytest --cov=./
after_success:
  bash <(curl -s https://codecov.io/bash)
  
